### PR TITLE
fix issue-#199

### PR DESCRIPTION
**Pull request by blue32captain**
fixed issue-#199.

### CODE REVIEW

**Review by oishun1112 — CHANGES_REQUESTED** [review]
please delete unnecessary files
- .idea/
- .infuraKey
- .key

**Comment by blue32captain** [comment]
Done.

**Comment by oishun1112** [comment]
the files still left

**Review by oishun1112 — APPROVED** [review]

**Comment by oishun1112** [comment]
https://github.com/code-423n4/2022-01-insure-findings/issues/21

**Pull request merged**
