### PR TITLE
Issue224

### PR DESCRIPTION
**Pull request by kohshiba**

### CODE REVIEW

**Comment by oishun1112** [comment]
https://github.com/code-423n4/2022-01-insure-findings/issues/277

**Comment by oishun1112** [comment]
https://github.com/code-423n4/2022-01-insure-findings/issues/250

**Comment by oishun1112** [comment]
https://github.com/code-423n4/2022-01-insure-findings/issues/224

**Comment by kohshiba** [comment]
new request created and close this one

**Pull request closed without merging**
